# -*- coding: utf-8 -*-
"""CV LAB-06

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wOpVxm4kGb8CTyfWjFmhdhkrKmttk2Lf
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
rmin, rmax = 100, 200

def show_images(original, without_background, with_background):
    plt.figure(figsize=(15, 5))

    plt.subplot(1, 3, 1)
    plt.imshow(original, cmap='gray') # Display as grayscale
    plt.title('Original Image')
    plt.axis('off')

    plt.subplot(1, 3, 2)
    plt.imshow(without_background, cmap='gray')
    plt.title('Slicing w/o Background')
    plt.axis('off')

    plt.subplot(1, 3, 3)
    plt.imshow(with_background, cmap='gray')
    plt.title('Slicing w Background')
    plt.axis('off')

    plt.show()

img = cv2.imread("/content/lotus.jpg")

img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

slicing_wo_background = np.zeros(img_gray.shape, dtype=np.uint8)
slicing_w_background = img_gray.copy()

for i in range(img_gray.shape[0]):
  for j in range(img_gray.shape[1]):
   pixel_value = img_gray[i][j]
   if rmin <= pixel_value <= rmax:
    slicing_wo_background[i][j] = 255
    slicing_w_background[i][j] = 0

show_images(img_gray, slicing_wo_background, slicing_w_background)